# =============================================================================
# CI Pipeline Workflow
# org-workflows/workflows의 reusable-ci 사용
# =============================================================================
#
# 스킵 방법:
#   - 커밋 메시지에 [skip ci], [ci skip], [no ci] 포함
#   - 문서만 변경 시 자동 스킵
#
# =============================================================================

name: CI Pipeline

on:
  push:
    branches:
      - develop
      - 'feature/**'
      - 'fix/**'
    paths:
      - 'src/**'
      - 'tests/**'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'src/**'
      - 'tests/**'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  ci:
    # [skip ci] 커밋 메시지 스킵
    if: |
      !contains(github.event.head_commit.message, '[skip ci]') &&
      !contains(github.event.head_commit.message, '[ci skip]') &&
      !contains(github.event.head_commit.message, '[no ci]')
    uses: org-workflows/workflows/.github/workflows/reusable-ci.yml@v1
    with:
      node-version: '20'
      run-lint: true
      run-tests: true
      run-build: true
      coverage-threshold: 80
    secrets: inherit
