# =============================================================================
# Migration Safety Check Workflow
# DB ë§ˆì´ê·¸ë ˆì´ì…˜ íŒŒì¼ ë³€ê²½ ì‹œ ì•ˆì „ì„±ì„ ê²€ì¦í•©ë‹ˆë‹¤.
# =============================================================================
#
# í•„ìˆ˜ ì„¤ì •:
#   - secrets.ANTHROPIC_API_KEY: Anthropic API í‚¤
#
# âš ï¸ ì£¼ì˜: ì´ ì›Œí¬í”Œë¡œìš°ëŠ” ë¶„ì„ë§Œ ìˆ˜í–‰í•©ë‹ˆë‹¤.
#          ì‹¤ì œ ë§ˆì´ê·¸ë ˆì´ì…˜ ì‹¤í–‰ì€ ìˆ˜ë™ ìŠ¹ì¸ í›„ ì§„í–‰í•´ì•¼ í•©ë‹ˆë‹¤.
#
# =============================================================================

name: Migration Safety Check

on:
  pull_request:
    paths:
      - 'migrations/**'
      - 'prisma/migrations/**'

jobs:
  analyze:
    name: Analyze Migration
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
      id-token: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Claude Code
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
      
      - name: Get Changed Migration Files
        id: migration-files
        run: |
          FILES=$(gh pr diff ${{ github.event.number }} --name-only | grep -E '(migrations|prisma)' || echo "")
          echo "files=${FILES}" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Analyze Migration Safety
        if: steps.migration-files.outputs.files != ''
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
          MIGRATION_FILES: ${{ steps.migration-files.outputs.files }}
        run: |
          claude -p "
            PR #${PR_NUMBER} ë§ˆì´ê·¸ë ˆì´ì…˜ ì•ˆì „ì„± ë¶„ì„
            
            ë³€ê²½ëœ ë§ˆì´ê·¸ë ˆì´ì…˜ íŒŒì¼: ${MIGRATION_FILES}
            
            ## ë¶„ì„ í•­ëª©
            1. ì˜í–¥ë°›ëŠ” í…Œì´ë¸”/ì»¬ëŸ¼ ì‹ë³„
            2. ì˜ˆìƒ ë½(Lock) ì‹œê°„
            3. ë°ì´í„° ì†ì‹¤ ê°€ëŠ¥ì„±
            4. ë‹¤ìš´íƒ€ìž„ í•„ìš” ì—¬ë¶€
            5. ëŒ€ëŸ‰ ë°ì´í„° ì²˜ë¦¬ ì—¬ë¶€
            
            ## ìœ„í—˜ë„ í‰ê°€ ê¸°ì¤€
            - ðŸŸ¢ Low: ë‹¨ìˆœ ì¶”ê°€ (ìƒˆ í…Œì´ë¸”, ìƒˆ nullable ì»¬ëŸ¼, ì¸ë±ìŠ¤)
            - ðŸŸ¡ Medium: ì»¬ëŸ¼ ìˆ˜ì •, ì œì•½ì¡°ê±´ ì¶”ê°€
            - ðŸŸ  High: ëŒ€ëŸ‰ ë°ì´í„° ë³€ê²½, ì»¬ëŸ¼ íƒ€ìž… ë³€ê²½
            - ðŸ”´ Critical: í…Œì´ë¸” ì‚­ì œ, ë°ì´í„° ì‚­ì œ, ìŠ¤í‚¤ë§ˆ ëŒ€í­ ë³€ê²½
            
            ## ì¶œë ¥
            1. PR ì½”ë©˜íŠ¸ë¡œ ë¶„ì„ ê²°ê³¼ ìž‘ì„±
            2. ë¡¤ë°± SQL ìŠ¤í¬ë¦½íŠ¸ ìƒì„± (migrations/rollbacks/ ë””ë ‰í† ë¦¬ì— ì €ìž¥)
            3. ìœ„í—˜ë„ì— ë”°ë¥¸ ë¼ë²¨ ì¶”ê°€
            4. High/Criticalì¸ ê²½ìš° @devops-team ë©˜ì…˜
            
            ## ë¼ë²¨ ì¶”ê°€
            gh pr edit ${PR_NUMBER} --add-label 'migration,needs-dba-review'
          "
      
      - name: Create Rollback Directory
        run: mkdir -p migrations/rollbacks
      
      - name: Generate Rollback Script
        if: steps.migration-files.outputs.files != ''
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
        run: |
          claude -p "
            PR #${PR_NUMBER}ì˜ ë§ˆì´ê·¸ë ˆì´ì…˜ì— ëŒ€í•œ ë¡¤ë°± ìŠ¤í¬ë¦½íŠ¸ ìƒì„±
            
            ## ìš”êµ¬ì‚¬í•­
            1. ê° ë§ˆì´ê·¸ë ˆì´ì…˜ì— ëŒ€ì‘í•˜ëŠ” ë¡¤ë°± SQL ìž‘ì„±
            2. íŒŒì¼ëª…: migrations/rollbacks/rollback_pr${PR_NUMBER}_$(date +%Y%m%d).sql
            3. ì‹¤í–‰ ìˆœì„œ ì£¼ì„ í¬í•¨
            4. ë°ì´í„° ë°±ì—… ëª…ë ¹ì–´ í¬í•¨ (í•„ìš”ì‹œ)
            
            ìƒì„±ëœ ë¡¤ë°± ìŠ¤í¬ë¦½íŠ¸ë¥¼ PR ì½”ë©˜íŠ¸ì—ë„ ì²¨ë¶€
          "
      
      - name: Commit Rollback Script
        if: steps.migration-files.outputs.files != ''
        run: |
          if [ -n "$(ls -A migrations/rollbacks/ 2>/dev/null)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add migrations/rollbacks/
            git commit -m "chore: add rollback script for PR #${{ github.event.number }}" || echo "No changes to commit"
            git push || echo "Nothing to push"
          fi
