# =============================================================================
# Deploy to Staging Workflow
# org-workflows/workflows의 reusable-deploy 사용
# =============================================================================
#
# 트리거:
#   - develop 브랜치 push (소스코드 변경 시만)
#   - 수동 실행 (workflow_dispatch)
#
# 스킵: 커밋 메시지에 [skip deploy], [no deploy] 포함
#
# =============================================================================

name: Deploy to Staging

on:
  push:
    branches:
      - develop
    paths:
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'
    paths-ignore:
      - '**.md'
      - 'docs/**'
  workflow_dispatch:

jobs:
  deploy:
    # [skip deploy] 커밋 메시지 스킵
    if: |
      !contains(github.event.head_commit.message, '[skip deploy]') &&
      !contains(github.event.head_commit.message, '[no deploy]')
    uses: org-workflows/workflows/.github/workflows/reusable-deploy.yml@v1
    with:
      environment: staging
      url: 'https://staging.ldmrepo.com'
      node-version: '20'
      run-health-check: true
      health-check-path: '/health'
      notify-slack: true
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
