# =============================================================================
# Deploy to Production Workflow
# org-workflows/workflows의 reusable-deploy 사용
# =============================================================================
#
# 트리거:
#   - GitHub Release 발행 (published)
#   - 수동 실행 (workflow_dispatch) - 확인 필수
#
# ⚠️ main 브랜치 push로는 자동 배포되지 않습니다!
#
# =============================================================================

name: Deploy to Production

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: '배포할 버전 (예: v1.0.0)'
        required: false
        type: string
      confirm:
        description: '프로덕션 배포를 확인합니다'
        required: true
        type: boolean
        default: false

jobs:
  deploy:
    # 수동 실행 시 confirm 체크 필수
    if: |
      github.event_name == 'release' ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.confirm == 'true')
    uses: org-workflows/workflows/.github/workflows/reusable-deploy.yml@v1
    with:
      environment: production
      url: 'https://ldmrepo.com'
      node-version: '20'
      run-health-check: true
      health-check-path: '/health'
      health-check-retries: 5
      notify-slack: true
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
